### ISSUE TITLE
Message to overwrite files

### ISSUE THREAD

**Issue by iulia-codes** [itemis/generator-xtext#14]
Running node v 6+ and the guide here: https://blogs.itemis.com/en/get-your-first-web-enabled-dsl-running-in-60-seconds

On attempting to run "yo xtext", the overwrite message appears. Maybe it could be clearer what user must do in this case, I have circled the word that is confusing.

![image](https://user-images.githubusercontent.com/940531/30066662-d80c8a08-9258-11e7-83cf-7f06ea92a267.png)

**Comment by franzbecker** [comment]
Thanks for creating the issue, unfortunately this cryptic choice is offered by the used framework (Yeoman).
I'll look into it - if we can maybe print out a proper message in this case.

For now I can only offer you this SO answer: https://stackoverflow.com/a/23153430
